# For module hosting facilities (rubygems, pypi, cpan) we set larger recheck time
# since there are a lot of links, but the links are unlikely to change status
# This list is |sort friendly, please keep sorted
"abf.io".generated_sampling_percentage = 10
"abf.io".recheck_generated = 21
"aur.archlinux.org".disable_head = true
"aur.archlinux.org".generated_sampling_percentage = 10
"bugs.freebsd.org".delay = 30               # 429s @ 3sec
"build.opensuse.org".generated_sampling_percentage = 10
"build.opensuse.org".recheck_generated = 21
"buildd.debian.org".delay = 60              # sensitive to load
"buildd.debian.org".generated_sampling_percentage = 1 # because of huge and large delay
"codeberg.org".delay = 30                   # 429s @ 30sec
"community.chocolatey.org".disable_head = true
"metacpan.org".aggregate = true
"metacpan.org".recheck_manual = 14
"crates.io".recheck_generated = 60
"crates.io".recheck_manual = 60
"crates.io".skip = true                     # misconfigured crap, always 404; XXX = this is true only for crate pages, not for e.g. https://crates.io/api/v1/crates/abscissa_core/0.5.2/download
"dev.exherbo.org".recheck_generated = 30    # broken, 60+ sec checks
"dev.exherbo.org".recheck_manual = 30       # broken, 60+ sec checks
"dev.exherbo.org".timeout = 5               # broken, 60+ sec checks
"dev.gentoo.org".delay = 1
"files.pythonhosted.org".delay = 1
"files.pythonhosted.org".generated_sampling_percentage = 1  # no real need to recheck links provided by pypi itself, right?
"files.pythonhosted.org".recheck_generated = 30
"files.pythonhosted.org".recheck_manual = 30
"git.alpinelinux.org".generated_sampling_percentage = 10
"git.pld-linux.org".generated_sampling_percentage = 10
"git.pld-linux.org".timeout = 5             # constant timeouts
"gitee.com".delay = 5                       # 429s @ 3sec
"gitee.com".generated_sampling_percentage = 10
"github.com".delay = 2
"github.com".generated_sampling_percentage = 1
"github.com".recheck_generated = 45
"github.com".recheck_manual = 30
"github.io".is = "github.com"
"githubusercontent.com".is = "github.com"
"gitlab.com".delay = 1
"hydra.nixos.org".generated_sampling_percentage = 1
"kojipkgs.fedoraproject.org".generated_sampling_percentage = 10
"lib.rs".disable_head = true                # https://gitlab.com/lib.rs/main/-/issues/209
"madoguchi.fyralabs.com".delay = 5          # 429s @ 3 sec
"marketplace.visualstudio.com".disable_head = true
"mpr.makedeb.org".disable_head = true
"notabug.org".delay = 60
"npmjs.com".delay = 10
"npmjs.org".delay = 10
"packages.altlinux.org".generated_sampling_percentage = 10
"packages.debian.org".generated_sampling_percentage = 10
"packages.guix.gnu.org".timeout = 5         # constant timeouts
"packages.msys2.org".disable_head = true
"packages.ubuntu.com".generated_sampling_percentage = 10
"packman.links2linux.org".disable_head = true
"pkgs.alpinelinux.org".generated_sampling_percentage = 10
"pkgs.alpinelinux.org".recheck_generated = 45
"pypi.org".delay = 1                        # lots of links, claims (XXX: source?) to handle much trafic
"pypi.org".recheck_manual = 14
"readthedocs.io".aggregate = true
"rubygems.org".delay = 1
"rubygems.org".recheck_manual = 14
"search.cpan.org".recheck_manual = 14
"sf.net".is = "sourceforge.net"
"sourceforge.io".is = "sourceforge.net"
"sourceforge.net".aggregate = true
"sources.debian.org".generated_sampling_percentage = 10
"src.fedoraproject.org".generated_sampling_percentage = 1
"static.crates.io".skip = false             # exclude this host from crates.io skip rule above

# Special blacklisted cases
"accounts.google.com".blacklist = true      # 302 redirect from dead sites.google.com

# Domain for sale, overtaken, spam etc.
# This list is |sort friendly, please keep sorted
"afflib.org".hijacked = true
"antigrain.com".hijacked = true
"aseman.co".hijacked = true
"astroid.org".hijacked = true
"beryl-project.org".hijacked = true
"boutell.co.uk".hijacked = true
"cdrkit.org".hijacked = true
"conduit-project.org".hijacked = true
"coolreader.org".hijacked = true
"cross-pcg.com".hijacked = true
"dejavu-fonts.org".hijacked = true
"directfb.org".hijacked = true
"ekg2.org".hijacked = true
"ferite.org".hijacked = true
"geocities.com".hijacked = true
"glimpse-editor.org".hijacked = true
"gnugadu.org".hijacked = true
"htdig.org".hijacked = true
"htpc-forum.de".hijacked = true
"jdebp.eu".hijacked = true
"jnickelsen.de".hijacked = true
"junoplay.com".hijacked = true
"kermit-project.org".hijacked = true
"kmldonkey.org".hijacked = true
"konst.org.ua".hijacked = true
"libcapn.org".hijacked = true
"mandriva.com".hijacked = true
"mepis.org".hijacked = true
"nimuh.com".hijacked = true
"ofset.org".hijacked = true
"opensync.org".hijacked = true
"opentnl.org".hijacked = true
"qtoctave.wordpress.com".hijacked = true
"somethingaboutorange.com".hijacked = true
"svn.mandriva.com".hijacked = true
"thekonst.net".hijacked = true
"tkzinc.org".hijacked = true
"topfx.com".hijacked = true
"wmii.de".hijacked = true
"yafray.org".hijacked = true
