[package]
name = "repology-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
serde = { version = "1.0.204", features = ["derive"] }
sqlx = { version = "0.8.0", default-features = false, features = ["derive", "migrate", "macros"] }
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"
